### ISSUE TITLE
SPA solver results returned without real matching info

### ISSUE THREAD

**Issue by jiangweiatgithub** [fmcooper/matchingproblems#1]
Hi,

How are you?

I just followed the sample command lines for SPA in readme, and got the solver results, but without any real matching info:

python F:\repos3\smp\frances_cooper\matchingproblems\matchingproblems-example-master\run_generator.py -numinst 5 -o ./spa_stl_10k_3_5a/instances -mp spa -n1 6 -n2 8 -n3 4 -pmin 3 -pmax 5 -t1 0.2 -t2 0.2 -skew 5 -lq 4 -uq 10 -llq 1 -lt 4 -luq 10 -twopl

6 8 4
1: (5 4) 3 8 7
2: 1 (7 2)
3: 4 3 2 1 7
4: 4 5 7
5: 4 3 5 7 2
6: (5 7) 3
1: 1: 2: 1
2: 1: 2: 1
3: 1: 1: 2
4: 1: 1: 2
5: 0: 1: 3
6: 0: 1: 3
7: 0: 1: 4
8: 0: 1: 4
1: 1: 1: 3: 3 2 5
2: 0: 1: 3: 4 (1 5) (3 6)
3: 0: 1: 2: (4 1) 6 5
4: 0: 1: 2: 5 (3 2) 4 6 1

instance generation parameters
number_of_agents_type_1: 6
number_of_agents_type_2: 8
number_of_agents_type_3: 4
min_pref_list_length: 3
max_pref_list_length: 5
ties_probability_1: 0.2
ties_probability_2: 0.2
sum_agent2_lower_quotas: 4
sum_agent2_upper_quotas: 10
skew_for_agent_1: 5.0
sum_agent3_lower_quotas: 1
sum_agent3_targets: 4
sum_agent3_upper_quotas: 10

python F:\repos3\smp\frances_cooper\matchingproblems\matchingproblems-example-master\run_solver.py -f ./spa_stl_10k_3_5a/instances/0.txt  -na 3 -bf

# Results for the run conducted on 14 Nov 2021, 11:34:19

# timings
time_model_creation_seconds: 0.005007
time_solve_seconds: 2.236607
time_total_seconds: 2.241614

# optimal matching statistics
optimal_size: 6
optimal_maxsizemincost: 9
optimal_maxsizemindegree: 3
optimal_maxsizeminsqcost: 17
optimal_generousmaxprofile: < 4 1 1 0 0 >
optimal_greedymaxprofile: < 4 1 1 0 0 >
optimal_greedyprofile: < 4 1 1 0 0 >
optimal_max_lec_abs_diff: 1
optimal_sum_lec_abs_diff: 2

Are the matching results supposed to be listed under "# optimal matching statistics"? (I seem to have got such info for the HR problem, etc.)

Thanks!
Wei

**Comment by fmcooper** [comment]
Hi Wei! 

In order to see results for this run, please exchange solver.get_results_long() for solver.get_results() in the final line of your file run_solver.py. This will then show results for the brute force executions. I have amended this in the readme.

Best wishes,

Frances
